name: Copy Commit

on: push

jobs:
  copy-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Copy Commit
        uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.DEPLOY_PERSONAL_ACCESS_TOKEN }}
        with:
          include: ''
          exclude: ''
          destination: 'RediatBrook/uactf-backend-deploy'
          branch: 'main'
